# Generated by Django 4.1.3 on 2022-12-06 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UCoE', '0002_class_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
    ]
