# Generated by Django 4.1.3 on 2023-03-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UCoE", "0010_staff_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff_feedback",
            name="feedback_reply",
            field=models.TextField(null=True),
        ),
    ]
