# Generated by Django 4.1.3 on 2023-03-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UCoE", "0013_student_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="student_feedback",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
