# Generated by Django 4.1.3 on 2023-03-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UCoE", "0014_student_feedback_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff_feedback",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
