# Generated by Django 4.1.3 on 2023-03-14 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UCoE", "0017_attendance_attendancereport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="cLass",
        ),
    ]
