# Generated by Django 4.1.3 on 2023-03-14 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("UCoE", "0018_remove_subject_class"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="staff",
        ),
        migrations.AddField(
            model_name="subject",
            name="staffs",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="UCoE.staff"
            ),
        ),
    ]
