# Generated by Django 4.1.3 on 2023-03-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UCoE", "0021_student_result"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session_Year",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_start", models.CharField(max_length=100)),
                ("session_end", models.CharField(max_length=100)),
            ],
        ),
    ]
